api/urls.py
from django.conf.urls import url

from api import views
app_name = "api"

urlpatterns = [
    url(r'^channels/', views.channels),
]

mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^polls/', include('polls.urls')),
    url(r'^admin/', admin.site.urls),
    #url(r'^my_talabat/', include('my_talabat.urls')),
    url(r'^tvguide/', include('tvguide.urls')),
    url(r'^api/', include('api.urls')),
]

tvguide/urls.py
from django.conf.urls import url

from . import views
app_name= "tvguide"

urlpatterns = [
    # ex: /polls/
    url(r'^$', views.index, name='index'),]

tvguide/models.py
from django.db import models


class Channel(models.Model):
    name = models.CharField(max_length=40)


class Category(models.Model):
    name = models.CharField(max_length=40)


class Program(models.Model):
    name = models.CharField(max_length=200)
    duration_in_minutes = models.IntegerField()
    release_year = models.IntegerField()
    category = models.ForeignKey(Category)


class TimeSlot(models.Model):
    start = models.DateTimeField()
    finish = models.DateTimeField()
    channel = models.ForeignKey(Channel)
    program = models.ForeignKey(Program)


class Genre(models.Model):
    name = models.CharField(max_length=40)


class ProgramGenre(models.Model):
    program = models.ForeignKey(Program)
    genre = models.ForeignKey(Genre)















# from django.db import models
#
#
# # Create your models here.
# class Channel(models.Model):
#     name = models.CharField(max_length=50)
#
#
#     def __str__(self):
#         return self.name
#
# class Category(models.Model):
#     name = models.CharField(max_length=200)
#
# class Program(models.Model):
#     name = models.CharField(max_length=200)
#     duration_in_minutes = models.IntegerField()
#     release_year = models.IntegerField()
#     category = models.ForeignKey(Category, on_delete=models.CASCADE)
#
#     def __str__(self):
#         return self.name
#
# class TimeSlot(models.Model):
#     start = models.DateTimeField('date published')
#     finish = models.DateTimeField('date published')
#     channel = models.ForeignKey(Channel)
#     program = models.ForeignKey(Program)
#
# class Genre(models.Model):
#     name = models.CharField(max_length=200)
#
# class ProgramGenre(models.Model):
#     program = models.ForeignKey(Program, on_delete=models.CASCADE)
#     genre = models.ForeignKey(Genre, on_delete=models.CASCADE)

tvguide/views.py
from django.shortcuts import render
from django.http.response import HttpResponse
# Create your views here.
from django.utils.dateparse import parse_datetime
from django.utils.datetime_safe import datetime

from tvguide.models import *


def index(request):
    now = datetime.now()
    timeslots = TimeSlot.objects.filter(finish__gt=now).order_by('start')[0:8]
    context = {'timeslots':timeslots , 'now':now}

    # time_start = TimeSlot.objects.filter(start="2017-04-07 20:15:00")
    # time_list = Program.objects.filter(timeslot__start__gte=parse_datetime('2017-04-07 20:15:00'))
    # context = {
    #     "time_list": time_list,
    #     "time_start" : time_start}

    return render(request, "tvguide/index.html", context)

    # channel_list = Channel.objects.all()
    # program_list = Program.objects.all()
    # category_list = Category.objects.all()
    # time_slot_list= TimeSlot.objects.all()
    # genre_list= Genre.objects.all()
    # programgenre_list= ProgramGenre.objects.all()
    # context = {
    #     'channel_list': channel_list,
    #     'program_list': program_list,
    #     'category_list': category_list,
    #     'time_slot_list' : time_slot_list,
    #     'genre_list' : genre_list,
    #     'programgenre_list' : programgenre_list,
    # }
    #question_count = question_list.count()
    #return render(request, "tvguide/index.html", context)

tvguide/templates/tvguide/index.html
{% extends 'polls/base.html'%}
{% load static %}

{% block header %}
{% load crispy_forms_tags %}

<h1> TVGUIDE Schedule </h1>
    <h2>{{ now }}</h2>
{% endblock %}


{% block content %}
<div class="panel panel-default">
    <div class="panel-heading">Programs</div>
    <div class="panel-body">
        {% for timeslot in timeslots %}
        <h2>{{ timeslot.program.name }}</h2>
        <h3> On {{ timeslot.channel.name }}</h3>
        <h4 class="text-danger">starts at {{ timeslot.start.time }} finish at {{ timslot.finish.time }} </h4>
            <h3>-----------------------------------------------</h3>
        {% endfor %}
    </div>
    <input class="btn btn-primary" type="submit" value="Next>>>"/>
</div>

{% endblock %}






{#    <body>#}
{#        <h1> TVGUIDE Schedule</h1>#}
{#        <h3> for {{ time_start }} </h3>#}
{##}
{#        {% for program in time_list %}#}
{#        <h4>{{ program.name }}</h4>#}
{#        <h4>{{ program.timeslot_set}}</h4>#}
{##}
{#        {% endfor %}#}
{##}
{#    </body>#}
{#</html>#}
{##}
{#{% for x in channel_list %}#}
{#        {{channel_list}}#}
{#        {{program_list}}#}
{#        {% endfor %}#}