api/urls.py
from django.conf.urls import url

from api import views
app_name = "api"

urlpatterns = [
    url(r'^channels/', views.channels),
]

mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^polls/', include('polls.urls')),
    url(r'^admin/', admin.site.urls),
    #url(r'^my_talabat/', include('my_talabat.urls')),
    url(r'^tvguide/', include('tvguide.urls')),
    url(r'^api/', include('api.urls')),
]

polls/urls.py
from django.conf.urls import url

from . import views
app_name= "polls"

urlpatterns = [
    # ex: /polls/
    url(r'^$', views.index, name='index'),
    url(r'^question/(?P<question_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^question/(?P<question_id>[0-9]+)/results/$', views.todo, name='results'),
    url(r'^question/(?P<question_id>[0-9]+)/edit/$', views.edit_question, name="edit"),
    url(r'^question/(?P<question_id>[0-9]+)/update/$', views.todo),
    url(r'^question/(?P<question_id>[0-9]+)/delete/$', views.delete_question , name="delete_question"),
    url(r'^question/new/$', views.add_question, name="add_question"),
    url(r'^question/choice/new/$', views.add_choice, name='add_choice'),
    url(r'^question/(?P<choice_id>[0-9]+)/edit_choice/$', views.edit_choice, name="edit_choice"),
    url(r'^question/(?P<choice_id>[0-9]+)/delete_choice/$', views.delete_choice, name="delete_choice"),
    url(r'^signin/$', views.signin, name='signin'),
    url(r'^register/$', views.register, name='register'),
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
    url(r'^use_api$', views.use_api, name='use_api'),
    url(r'^use_api2', views.use_api2, name='use_api2'),
    url(r'^maps', views.maps, name='maps'),
#     url(r'^question/create/$',views.todo),
#     url(r'^choice/(?P<choice_id>[0-9]+)/edit/$', views.todo),
#     url(r'^choice/(?P<choice_id>[0-9]+)/update/$', views.todo),
#     url(r'^choice/(?P<choice_id>[0-9]+)/delete/$', views.todo),
#     url(r'^choice/new/$', views.todo),
#     url(r'^choice/create/$',views.todo),
    ]


    # url(r'^question/(?P<question_id>[0-9]+)/results/$', views.detail, name='results'),
""""# ex: /polls/5/
   url(r'^(?P<question_id>[0-9]+)/$', views.detail, name='detail'),
   # ex: /polls/5/results/
   url(r'^(?P<question_id>[0-9]+)/results/$', views.results, name='results'),
   # ex: /polls/5/vote/

   url(r"^check/(?P<stuff>[a-zA-Z0-9]+)/(?P<more>[0-9]+)/(?P<araboo>.+)$", views.itworks),"""

polls/models.py
from django.contrib.auth.models import User
from django.db import models


# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    owner = models.ForeignKey(User)
    slug = models.CharField(max_length=255)

    def __str__(self):
        return self.question_text


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=20)

    def __str__(self):
        return "%s (choice for %s)" % (self.choice_text, self.question.question_text)

polls/forms.py
from django import forms
from django.contrib.auth.models import User

from polls.models import Question, Choice


class Myform(forms.Form):
    question_name = forms.CharField(max_length=200, min_length=1, required=True)


    #name = forms.CharField(max_length=200, min_length=1, required=True)
    # telephone_number = forms.CharField(max_length=8, min_length=8, required=True, help_text="enter digits only")
    # email= forms.EmailField()
    # gender= forms.ChoiceField(choices=[(None,"Select a gender"),("M","Male"),("F","Female")])
    # agree=forms.BooleanField(required=True, label="I agree on the terms and conditions")

class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ["question_text"]

class ChoiceForm (forms.ModelForm):
    class Meta:
        model= Choice
        fields= ["question", "choice_text"]
        labels = {
            'question': 'choose a question',
            'choice_text' : 'Enter a choice'
        }
        widgets = {'question' : forms.HiddenInput}

class SigninForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

class SignupForm(forms.ModelForm):
    class Meta:
        model = User
        fields = {'first_name', 'last_name', 'email', 'username', 'password'}
        widgets = {'password': forms.PasswordInput}

polls/views.py
from django.contrib import messages
from django.contrib.auth import login, authenticate
from django.shortcuts import render, redirect
from django.utils import timezone

from polls import forms
from polls.models import Question, Choice
from django.http.response import HttpResponse, HttpResponseRedirect
from polls.forms import Myform



def index(request):
    question_list = Question.objects.all()
    question_count = question_list.count()
    if request.method == 'GET':
        form = Myform()
        context = {"questions":question_list, "question_count":question_count,"form":form}
        return render(request, "polls/index.html", context)
    elif request.method == 'POST':
        form = Myform(request.POST)
        if form.is_valid():
            question_text = form.cleaned_data['question_name']
            q = Question(question_text=question_text, pub_date=timezone.now())
            q.save()
            messages.add_message(request, messages.SUCCESS, "You have successfully added a poll")

            return redirect(request, "polls:index")
            #return render(request, "polls/ok.html")
        else:
            messages.add_message(request, messages.WARNING, "There was an error in your form")
            context = {"questions":question_list, "question_count":question_count,"form":form}
            return render(request, "polls/index.html", context)
    else:
        return render(request, "polls/oops.html")



'''latest_question_list = Question.objects.order_by('-pub_date')[:5]
    output = ', '.join([q.question_text + "  " + str(q.pub_date) for q in latest_question_list])
    return HttpResponse(output)'''


def detail(request, question_id):
    q = Question.objects.get(id=question_id)
    return render(request, "polls/detail.html", {'question': q})


def vote(request, question_id):
    choice_id = request.POST.get("choice")
    choice = Choice.objects.get(id=choice_id)
    choice.votes += 1
    choice.save()
    context = {"choice":choice, "question":Question.objects.get(id=question_id)}
    #return HttpResponse("%s has %d votes" %(choice, choice.votes))
    #return HttpResponseRedirect(redirect_to=reverse('results', args=[question_id]))
    return render(request, "polls/vote.html", context)


def results(request, question_id):
    q = Question.objects.get(id=question_id)
    return HttpResponse('showing results')

def itworks(request, stuff,more,araboo):
    context= [stuff,more,araboo]
    return render(request, "polls/itworks.html", {'cont':context})
        #HttpResponse("<h1> It Works!</h1><h1>Stuff is %s </h1><h2>more is %s</h2><h2>anything is %s</h2>" %(stuff,more,araboo))

def todo(request):
    pass

def add_question(request):
    if request.method == 'GET':
        form = Myform()
        context = {"form":form}
        return render(request, "polls/add_question.html", context)
    elif request.method == 'POST':
        form = Myform(request.POST)
        if form.is_valid():
            question_text = form.cleaned_data['question_name']
            q = Question(question_text=question_text, pub_date=timezone.now(), owner=request.user)
            q.save()
            messages.add_message(request, messages.SUCCESS, "You have successfully added a poll")
            return redirect('polls:index')
            #return render(request, "polls/ok.html")
        else:
            messages.add_message(request, messages.WARNING, "There was an error in your form")
            context = {'form': form}
            return render(request, "polls/add_question.html", context)
    else:
        return render(request, "polls/oops.html")



def edit_question(request, question_id):
    question = Question.objects.get(id=question_id)
    add_choice_form = forms.ChoiceForm(initial={'question':question})
    if request.method == "GET":
        form = forms.QuestionForm(instance=question)
        context = {
            "question" : question,
            "form": form,
            "choice_form": add_choice_form
        }
        return render(request, "polls/edit_question.html",context)

    elif request.method == "POST":
        form = forms.QuestionForm(request.POST, instance=question)
        if form.is_valid():
            form.save()
            messages.add_message(request, messages.SUCCESS, "Edit successful")
            return redirect('polls:edit_question', question_id=question_id)
            # return render(request, "polls/ok.html")
        else:
            messages.add_message(request, messages.WARNING, "Something is wrong")
            context = {'question': question,
                       'form': form ,
                       "choice_form": add_choice_form}
            return render(request, "polls/edit_question.html", context)


def add_choice(request):
    form = forms.ChoiceForm(request.POST)
    if form.is_valid():
        choice = form.save()
        return redirect('polls:edit', question_id= choice.question.id)
        # return redirect('/polls/question/%s/edit'%(choice.question.id))
    else:
        return redirect ("polls:index")


def delete_question(request, question_id):
    if request.method == "POST":
        question = Question.objects.get(id=question_id)
        if question.owner == request.user:
            question.delete()
            messages.add_message(request, messages.WARNING, "Question Gone!")
            return redirect("polls:index")
        else:
            return redirect("polls:oops")
    else:
        return redirect("polls:index")


def delete_choice(request, choice_id):
    if request.method == "POST":
        choice = Choice.objects.get(id=choice_id)
        choice.delete()
        messages.add_message(request, messages.WARNING, "Choice Gone!")
        return redirect("polls:edit", choice.question.id)
    else:
        return redirect("polls:detail")



def edit_choice(request, choice_id):
    choice = Choice.objects.get(id=choice_id)
    if request.method == "GET":
        form_obj = forms.ChoiceForm(instance=choice)
        context = {
            "choice" : choice,
            "form": form_obj,
        }
        return render(request, "polls/edit_choice.html",context)

    elif request.method == "POST":
        form = forms.ChoiceForm(request.POST, instance=choice)
        if form.is_valid():
            form.save()
            messages.add_message(request, messages.SUCCESS, "Edit successful")
            return redirect('polls:edit', question_id=choice.question.id)
            # return render(request, "polls/ok.html")
        else:
            messages.add_message(request, messages.WARNING, "Something is wrong")
            context = {'choice': choice,
                       'form': form ,
                       }
            return render(request, "polls/edit_choice.html", context)

def signin(request):
    if request.method == 'GET':
        form = forms.SigninForm()
        context = { 'form' : form }
        return render(request, "polls/signin.html", context)
    else:
        form = forms.SigninForm(request.POST)
        if not form.is_valid():
            messages.add_message(request, messages.WARNING, "Invalid form data, try again")
            context = {'form': form}
            return render(request, "polls/signin.html", context)
        # form is valid, so, proceed
        username = form.data.get("username")
        password = form.data.get("password")
        user = authenticate(username=username, password=password)
        if user is None:
            messages.add_message(request, messages.WARNING, "Invalid userid/password")
            context = {'form': form}
            return render(request, "polls/signin.html", context)
        # user is authenticated
        login(request, user)
        messages.add_message(request, messages.SUCCESS, "You are now logged in")
        return redirect("polls:index")


def register(request):
    if request.method == 'GET':
        form = forms.SignupForm()
        context = {'form': form}
        return render(request, "polls/register.html", context)
    else:
        form = forms.SignupForm(request.POST)
        if not form.is_valid():
            messages.add_message(request, messages.WARNING, "Invalid form data, try again")
            context = {'form': form}
            return render(request, "polls/register.html", context)
        # form is valid, so, proceed
        password =form.data.get("password")
        user = form.save()
        user.set_password(password)
        user.save()
        messages.add_message(request, messages.SUCCESS, "User Created")
        return redirect("polls:register")

def use_api(request):
    import requests
    # url = "http://api.github.com/events"
    # r = requests.get(url)
    # events = r.json()
    # context = {'events': events}
    return render(request, "polls/use_api.html", {})


def use_api2(request):
    import requests
    code = request.GET.get("code")
    url = "https://api.instagram.com/oauth/access_token"
    r = requests.post(url, data={
        'client_id':'29c4170223c24304b159d0d3b4546579',
        'client_secret':'3628fbe4f4af4badade334945ee2ba62',
        'grant_type':'authorization_code',
        'redirect_uri' : 'http://localhost:8000/polls/use_api2/',
        'code': code,
    })
    # print("code is" + code)
    return render(request, "polls/use_api2.html", {"code":code, "r":r, "u":r.json()})

# def InstaUser(AbstractBaseUser):
#     access_token =

def maps(request):
    return render(request, "polls/maps.html", {})

polls/templates/polls/add_question.html
{% extends 'polls/base.html'%}
{% load crispy_forms_tags %}
{% block header %}
<h3>My Awesome Form</h3>
{% endblock %}

{% block content %}
<div class="panel panel-default">
    Form goes here
    <form action="{% url 'polls:add_question' %}" method="POST">
        {% csrf_token %}
        {{ form | crispy}}
        <!--<h4>{{ form.as_p }}</h4>-->

        <input class="btn btn-primary" type="submit"/>
    </form>
</div>

{% endblock %}

polls/templates/polls/base.html
<!DOCTYPE html>

{% load static %}
<html lang="en">

    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
        <title>The polls app</title>

        <!-- Bootstrap -->
        <link href="{% static 'polls/bootstrap-3.3.7-dist/css/bootstrap.css' %}" rel="stylesheet"/>
        <style>
     h1{text-align:center}



        </style>
    </head>

    <body>


        <!-- /.container -->


        <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->

        {% if messages %}
        {% for message in messages %}
        <div class="alert alert-{{message.tags}}">
            {{message}}
        </div>
        {% endfor %}
        {% endif %}

        <div class="container">
            <br>
            <div class="jumbotron text-center">

                    {% block header %}
                    {% endblock %}

            </div>

            {% block content %}
            {% endblock %}

        </div>


    </body>
</html>

polls/templates/polls/detail.html
{% extends 'polls/base.html'%}
{% load static %}
{% block header %}
<h3>Question : {{question}}</h3>
{% endblock %}

{% block content %}
<div class="panel panel-default">

    <form  action="{% url 'polls:vote' question.id %}" method="post">
        {% csrf_token %}
        {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" value="{{ choice.id }}">
        <label>{{ choice.choice_text }}</label>
        <br>
        {% endfor %}
        <input type="submit" value="Vote"/>
    </form>
    <a href="{% url 'polls:index' %}"> Back to main</a>
</div>

{% endblock %}

polls/templates/polls/edit_choice.html
{% extends 'polls/base.html'%}
{% load crispy_forms_tags %}

{% block header %}
{{ question.question_text }}
{% endblock %}

{% block content %}


<h1> Edit the Choice</h1>


<form action="{% url 'polls:edit_choice' choice.id %}" method="POST">
                    {% csrf_token %}
                    {{ form | crispy }}
                    <input class="btn btn-primary"
                           type="submit"
                           value="Edit"/>
</form>


{% endblock %}

polls/templates/polls/edit_question.html
{% extends 'polls/base.html'%}
{% load crispy_forms_tags %}

{% block header %}
{{ question.question_text }}
{% endblock %}

{% block content %}
<div class="panel panel-default">
    Form goes here
    <form action="{% url 'polls:edit' question.id %}" method="POST">
        {% csrf_token %}
        {{ form | crispy}}
    <input type="submit">
    </form>
</div>

<h1> choices:</h1>
{% for choice in question.choice_set.all %}
<h2> {{ choice.choice_text}}</h2>

  <a href="{% url 'polls:edit_choice' choice.id %}" class="btn btn-primary">Edit</a>
<form action="{% url 'polls:delete_choice' choice.id %}" method="POST">
                    {% csrf_token %}
                    <input class="btn btn-danger"
                           type="submit"
                           value="Delete"/>

</form>
{% endfor %}

<form action="{% url 'polls:add_choice' %}" method="post">
    {% csrf_token %}
    {{ choice_form | crispy }}
    <input type="submit" class="btn" value="Add a choice!">

</form>



{% endblock %}

polls/templates/polls/index.html
{% extends 'polls/base.html'%}
{% load static %}
{% block header %}
{% load crispy_forms_tags %}

<h1> {{question_count}} polls waiting! </h1>
{% endblock %}

{% block content %}
<div class="panel panel-default">
{% if  user.is_authenticated %}
<a href="{% url 'polls:signin' %}" class="btn">Sign Out</a>
    {% else %}
    <a href="{% url 'polls:signin' %}" class="btn">Sign In</a>
        {% endif %}

    <div class="panel-heading">Recent polls</div>
    <div class="panel-body">
        {% for question in questions %}
        <div class="row">
            <div class="col col-xs-6 col-sm-8">
                <h4>{{question.question_text}}</h4>
                <p>{{ question.pub_date }} made by {{ question.owner }}</p>

            </div>
            <div class="col col-xs-6 col-sm-4">
                <!--<a href="{{q.id}}" class="btn btn-primary">view poll</a>-->
                <a href="{% url 'polls:detail' question.id %}" class="btn btn-primary">view poll</a>
                <a href="{% url 'polls:edit' question.id %}" class="btn btn-primary">Edit</a>
                <form action="{% url 'polls:delete_question' question.id %}"
                      method="post" style="display: inline-block">
                    {% csrf_token %}
                    {% if question.owner == request.user %}
                    <input class="btn btn-danger"
                           type="submit"
                           value="Delete"/>
                    {% endif %}

                </form>
            </div>

        </div>
        {% endfor %}
    </div>
</div>

<div class="panel panel-default">
    <div class="panel-heading">Make your own poll</div>
    <div class="panel-body">
                    <form action="{% url 'polls:add_question' %}" method="POST">
                        {% csrf_token %}
                        {{ form | crispy}}
                        <!--<h4>{{ form.as_p }}</h4>-->

                        <input class="btn btn-primary" type="submit" value="Add it"/>
                    </form>



            </div><!-- /input-group -->
        </div><!-- /.col-lg-6 -->



<br/>
{% endblock %}

polls/templates/polls/itworks.html
{% extends 'polls/base.html'%}
{% load static %}

{% block header %}
<h3>It Works!</h3>
{% endblock %}

{% block content %}
<div class="panel default-panel">
{% for x in cont %}
<h2>{{x}}</h2>

{% endfor %}
</div>
{% endblock %}

<!--<h2> {{a}} </h2>-->
<!--<h2> {{b}} </h2>-->
<!--<h2> {{c}} </h2>-->

polls/templates/polls/maps.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Title</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
              integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
              crossorigin="anonymous">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css"
              integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp"
              crossorigin="anonymous">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.5.0/Chart.js"></script>
    </head>

    <body>
        <h2>Thats your Geolocation by google maps api dynamic streetview and fixed sateliteview!</h2>
        <h3>Your current location is <b id="loc">unknown</b></h3>

        <div>
            <iframe id="mymovmap"
                    width="600"
                    height="450"
                    frameborder="0"
                    style="border:0">
                //the src was a specific location in the next line but we commented it out to make it move to
                // the ceter of the location we are watching (changes to the customer location shown in url2 below)
                // pre-defined location with a dynamic google map: src =
                //"https://www.google.com/maps/embed/v1/place?key=AIzaSyDd8uNk64SQ1B1z-ZKBhKP1Zy_q1QtXtys&q=29.3789917,47.9910573"allowfullscreen>
                //in the upper line: after the q is the longitude and latitude where you can paste other locations
                // if you want it fixed dont forget to take off url2 from the script below
            </iframe>
        </div>
        <img id="mymap" width="600px" height="600px">
        <script>
            var options = {
                enableHighAccuracy: true,
                timeout: 5000,
                maximumAge: 0
            };
            //to follow the location of the user and show it on the map (watchPosition) instesd of (getPosition)
            navigator.geolocation.watchPosition(
                function (pos) {
                    console.log("got position");
                    console.log(pos);
                    var center = pos.coords.latitude + "," + pos.coords.longitude;
                    //var markers = "color:blue"
                    var url = "https://maps.googleapis.com/maps/api/staticmap?center=" + center + "&zoom=18&size=400x300&maptype=satellite";
                    var url2 = "https://www.google.com/maps/embed/v1/place?key=AIzaSyDd8uNk64SQ1B1z-ZKBhKP1Zy_q1QtXtys&q=" + center;
                    //"markers=" + encodeURIComponent(markers);
                    document.getElementById("mymap").src = url;
                    document.getElementById("loc").innerHTML = center;
                    document.getElementById("mymovmap").src = url2;
                },
                function (err) {
                    console.warn("cannot get position");
                    console.warn(err);
                },
                options)


        </script>


    </body>

</html>

polls/templates/polls/ok.html
{% extends 'polls/base.html'%}

{% block header %}
OK
{% endblock %}

polls/templates/polls/oops.html
{% extends 'polls/base.html'%}

{% block header %}
OK
{% endblock %}

polls/templates/polls/questions.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Title</title>
    </head>
    <body>
        
    </body>
</html>

polls/templates/polls/signin.html
{% extends 'polls/base.html'%}
{% load crispy_forms_tags %}
{% block header %}
<h3>Please fill in the form to sign in</h3>
{% endblock %}

{% block content %}
<div class="panel panel-default">
    Form goes here
    <form action="{% url 'polls:signin' %}" method="POST">
        {% csrf_token %}
        {{ form | crispy}}
        <!--<h4>{{ form.as_p }}</h4>-->

        <input class="btn btn-primary" type="submit" value="sign in"/>
    </form>
</div>

{% endblock %}

polls/templates/polls/use_api.html
{% extends 'polls/base.html' %}
{% load static %}
{% block header %}
    testing api's
{% endblock %}

{% block content %}
        <a href="https://api.instagram.com/oauth/authorize/?client_id=29c4170223c24304b159d0d3b4546579&redirect_uri=http://localhost:8000/polls/use_api2/&response_type=code">Redirect</a>

{% comment %}
{% for event in events %}
<img src="{{ event.actor.avatar_url }}">
{% endfor %}
{% endcomment %}
{% endblock %}

{#event.actor.avatar_url#}

polls/templates/polls/vote.html
{% extends 'polls/base.html'%}
{% load crispy_forms_tags %}
{% block header %}
<h3>{{ question.question_text }}</h3>
    <h3>{{ choice.choice_text }} : {{ choice.votes }} votes</h3>
{% endblock %}

{% block content %}

{% endblock %}